### ISSUE TITLE
Versiones de apps en ERPNext

### ISSUE THREAD

**Issue by federicocalvo** [fproldan/erpnext#1]
Cuando bajamos alguna actualización, erpnext nos muestra un mensaje con los cambios y el núevo número de la versión de lo que haya actualizado.

Esto lo hace por usuario, y es muy bueno para evitar el problema de que ciertos usuarios no se enteran de los cambios.

Averiguar como se puede hacer para que subamos los agregados y cambiemos los números en nuestras actualizaciones. Ver como trabaja esto para que podamos usarlo.

# Test
App: Cheques
Rama: version_change

Hacer hardcore migrate a esa rama y ver si cuando nos logeamos en el sitio nos sale el cartel del cambio.

**Comment by Don-Leopardo** [comment]
Al parecer la cosa es: Cambiar en el hook la version y en el __init__ de la app. Luego, generar una carpeta change_log en la carpeta donde estan los modulos. Dentro de esa carpeta, generar carpetas con el nombre del estilo v{nro_major_version} (v10 v11 v5 v6). Dentro de esas carpetas crear archivos .md con nombres del estilo v{nro_completo_version_separado_por_guiones_bajos} (v10_1_2.md) que contengan el texto a mostrar.

En teoria esto deberia funcionar

**Comment by Don-Leopardo** [comment]
[Uploading... Captura de pantalla 2019-02-21 a la(s) 12.25.36.png ]

**Comment by Don-Leopardo** [comment]
![Captura de pantalla 2019-02-21 a la(s) 12.25.36.png](https://images.zenhubusercontent.com/5c61987be11cd566ed0fffb1/97ccd4d5-3d70-4fae-8ac8-17b2efb1590b)

**Comment by federicocalvo** [comment]
@fproldan esto hay que documentarlo en snipetslab?

**Comment by ValentinaPruvost** [comment]
### Resultados de Testing
---

- [ ] **Problema encontrado:** No apareció ningún cartel
**URL en la que ocurrió:** 
**Cómo reproducirlo:**

**Comment by Don-Leopardo** [comment]
@federicocalvo Queres que lo documente en la wiki de github o en algún otro lado? Avisame, así cierro el issue.

**Comment by federicocalvo** [comment]
@Don-Leopardo por eso le pregunte a @fproldan , no para que este en la wiki, sino en snipetslab más vale.

**Comment by fproldan** [comment]
@Don-Leopardo  Agregalo acá asi nos queda todo junto. https://bitbucket.org/dashboard/snippets

**Comment by Don-Leopardo** [comment]
Listo:
https://bitbucket.org/snippets/diamoerp/6e5kej/cartel-de-cambios-de-version
