### ISSUE TITLE
Balance General no ordena por fecha en By Voucher

### ISSUE THREAD

**Issue by federicocalvo** [fproldan/erpnext#10]
El Balance General (General Ledger), cuando selecciona la opción de ordenado By Voucher, no estaría ordenando los asientos por fecha.

Ver si se puede deducir algo, si nosotros podemos llegar a modificarlo, duplicarlo o ver si tenemos que hacer un issue.

**Comment by Don-Leopardo** [comment]
@federicocalvo
Hice el issue de todos modos: https://github.com/frappe/erpnext/issues/17707
Pero la idea es rehacer lo que se necesita en el nuevo reporte.

**Comment by Don-Leopardo** [comment]
https://github.com/frappe/erpnext/pull/17845
