### ISSUE TITLE
[BUG] Make from Lead to Opportunity

### ISSUE THREAD

**Issue by fproldan** [fproldan/erpnext#12]
## Make from Lead to Opportunity

 Issue https://github.com/frappe/erpnext/issues/17722

## Testing

- Crear una iniciativa
- En la iniciativa ir a Make > Oportunidad
- Debe completar el campo Oportunidad desde e Iniciativa

**Comment by Don-Leopardo** [comment]
https://github.com/frappe/erpnext/pull/17727
Se puede testear en Demo1
