### ISSUE TITLE
Revisar textos de la web nueva

### ISSUE THREAD

**Issue by fproldan** [fproldan/erpnext#16]
- Ver faqs, si hacen falta o modificar/sacar

web.diamo.com.ar

**Comment by AleGauna** [comment]
Ya estan las modificaciones y algún texto nuevo en la carpeta planificacion

**Comment by AleGauna** [comment]
Redactar texto de Precio de implementación

**Comment by federicocalvo** [comment]
@AleGauna fijate si podes mirar los textos de frappe por lo menos por la gramática
