### ISSUE TITLE
Consulta de código

### ISSUE THREAD

**Issue by fproldan** [fproldan/erpnext#2]
@AleGauna commented on [Tue Feb 26 2019](https://github.com/fproldan/factura-electronica-ar/issues/35)

Entrar a solicitud de materiales y ver que filtro aplica el campo que trae los productos. 

Cuestion: Los productos que son a manufacturar no los trae. Si se les puede hacer una solicitud de mat desde el doctype y no tira error en ningún lado.

**Comment by Don-Leopardo** [comment]
Estuve leyendo esto de onda y no termino de entender donde "trae" los productos. En el campo de la tabla hija de productos, el filtro para el select es:
No cancelado
Habilitado
Y con fecha de "end of life" mayor a hoy o vacía
Después tiene otros filtros, pero son difíciles de rastrear porque se arman al vuelo. Si es ese el lugar donde debería mirar, los puedo rastrear.

**Comment by AleGauna** [comment]
Con el término "trae" los productos me refiero a aquellos que se pueden seleccionar de esa tabla hija y cuales no pasan el filtro. Me refería a eso, me pareció que se entendía más.
Y uno de esos filtros esta haciendo que no pueda seleccionar los productos que se manufacturan en una solicitud de materiales. 
Buscando a prueba y error encontré que filtra los productos que no tienen el tilde que indica que son productos para la compra, independientemente que se produzcan.

**Comment by Don-Leopardo** [comment]
Bueno, ahora me fijo bien cuál es exactamente el filtro de eso y lo pongo acá.

**Comment by Don-Leopardo** [comment]
tabItem.docstatus < 2
and tabItem.has_variants=0
and tabItem.disabled=0
and (tabItem.end_of_life > %(today)s or ifnull(tabItem.end_of_life, '0000-00-00')='0000-00-00')
and `tabItem`.is_purchase_item = 1.0 

Esos son los filtros, la traducción sería:
Item no cancelado
Item sin variantes
Item habilitado
Item con fecha de "end of life" mayor a hoy o vacía
Item de compra
