### ISSUE TITLE
Integracion Mailchimp/Diamo

### ISSUE THREAD

**Issue by fproldan** [fproldan/erpnext#26]
- Agregar etiqueta **"iniciativa"** si el estado de la inciativa es iniciativa.
- **"oportunidad"** cuando el estado de la inciativa sea oportunidad.
-  **"cotizacion"** cuando el estado de la iniciativa es cotizacion.
- **"convertido"** cuando el estado es converttido.

Siempre debe tener una etiqueta, por lo que hay que ir borrando las que tenga.

Pregunta Fede: ¿Se puede disparar X dias despues que cambia el estado, para demorar el aviso a Mailchimp? Como que mailchimp se entere 20 días tarde que cambio de iniciativa a oportunidad.

**Comment by Don-Leopardo** [comment]
@federicocalvo @fproldan Debería agregar a la lista aquellos leads generados a mano?

**Comment by Don-Leopardo** [comment]
@federicocalvo espero los resultados de tu test, ya esta instalado
