### ISSUE TITLE
Ver y configurar una API key de google en Delivery Trip

### ISSUE THREAD

**Issue by federicocalvo** [fproldan/erpnext#32]
Investigar y colocar una api key que funcione para Delivery Trip

Configuración:
https://erp.diamo.com.ar/desk#Form/Google%20Maps%20Settings

Doctype:
https://erp.diamo.com.ar/desk#List/Delivery%20Trip/List

**Comment by Don-Leopardo** [comment]
Al parecer es gratis pero google te obliga a meterle la info de la tarjeta para su DB

**Comment by federicocalvo** [comment]
@Don-Leopardo en demo, deje un viaje de entrega en borrador donde presionando las dos opciones tira errores de conversión y el otro es más general, para ver que se puede hacer o si los corrigieron los indu en alguna versión.

https://demo.diamo.com.ar/desk#Form/Delivery%20Trip/TOUR-00004

**Comment by federicocalvo** [comment]
- Configurar Google Maps
- Agregar la unidad de medida que queremos (KILOMETRO por ejemplo)
- Agregar en la configuración Global donde dice distancia por defecto, los KILOMETROS
- Agregar la conversión en Factor de Conversión de Unidad de Medida
