### ISSUE TITLE
Facilitar la importación del plan de cuenta

### ISSUE THREAD

**Issue by federicocalvo** [fproldan/erpnext#4]
Averiguar como es el tema de importación de un plan de cuentas (Chart of account o COA para buscar) por JSON, o como están importando los planes de cuenta en el foro.

La idea principal es que el cliente nos pudiera mandar un Excel o CSV, con una estructura que le mandemos (Numero, cuenta y padre en teoría).

De esta forma, en el momento que sea (levantando la instancia, luego del wizzard, etc antes de que se empiece con la capacitación) tener el plan de cuenta cargado.

# Implementación:

Dentro del FAT se incluirá una utilidad que tomará un CSV, lo convertirá en JSON y lo guardará en la carpeta correcta del ERP para que pueda ser utilizado como COA desde el wizzard.

## Consideraciones:

- Archivo CSV separado con ; (punto y coma)
- Números separados por puntos
- Primer numero debe tener un solo dígito

## Pasos:

- Entrar a la lista de sitios y buscar el sitio deseado
- Adjuntar el CSV en el sitio
- Apretar en el botón "Generar Chart of Accounts"
- Esperar a un cartel
- Si el cartel dice que esta listo, lo estará.
- Si el cartel no aparece tras un tiempo considerable o aparece con un error, deberá entrar a la lista de errores del ERP y ver lo sucedido. Si no hay nada en ninguna de las dos listas (error log y errores de instantánea) puede comprobar en "Trabajos en segundo plano" si es que aun esta en ejecución.

**Comment by Don-Leopardo** [comment]
https://discuss.erpnext.com/t/how-to-import-chart-of-account-csv-file/39211/12
Según ese post, hay que crear los csv ordenados y borrar todas las cuentas excepto la root para que funcione.

Encontre varios hablando de J(jota)son pero en ninguno dicen como usarlos. Según entiendo simplemente sugieren que los mandes a chart.erpnext.com o que los agregues a tu propio código y después crees una nueva compañía. Algo que me parece bastante malo, pero si pinta lo investigo (confirmar).

**Comment by federicocalvo** [comment]
@Don-Leopardo después analizate esto que me parece que viene por acá, fijate que lo están haciendo y tiene cierta lógica, a menos que no este entendiendo algo:

https://discuss.erpnext.com/t/how-to-apply-use-a-coa-from-https-charts-erpnext-com/23780

https://discuss.erpnext.com/t/can-you-delete-the-json-file-of-a-coa-after-initial-setup-is-finished/41416

**Comment by Don-Leopardo** [comment]
@federicocalvo
Como decía, hay que agregarlo al código. Estaba pensando que se puede hacer una funcionalidad desde el nuevo Frappe Administration Tool (#3). Que permita cargar un json y copiarlo a la carpeta necesaria del ERP (apps/erpnext/accounts/doctype/account/chart_of_accounts/).
La pregunta es: Los clientes van a saber hacer un json o de dónde pensas sacarlo?

**Comment by Don-Leopardo** [comment]
Se debería hacer un algoritmo que, a partir de los números con punto del nombre de las cuentas del plan de cuentas, determine el orden dentro del árbol y asigne el padre de cada cuenta.

El algoritmo recibiría un csv, lo convertiría a json y agregaría los padres de cada cuenta. Además, lo copiaría a la carpeta de planes de cuenta del ERP para que esté listo para usarse en el wizard y debería permitir descargarlo también.

**Comment by Don-Leopardo** [comment]
Consideraciones:
- Archivo CSV separado con ; (punto y coma)
- Numeros separados por puntos
- Primer numero debe tener un solo digito
