### ISSUE TITLE
Reports allignment issue in Arabic Interface

### ISSUE THREAD

**Issue by FlexsoftsTech** [fproldan/erpnext#4]
Dear Team, all reports do not work probably on Arabic interface, there issue in columns name alignment with columns content and total amount showing Zero even though there is amounts in the columns, in English interface it is working fine, this issue happening in all reports
kindly this is very urgent, we receiving daily questions about this issue 
![reports issue](https://user-images.githubusercontent.com/33314211/53480164-aaaf6f80-3a8b-11e9-9542-64ebb02c9581.png)

**Comment by fproldan** [comment]
@FlexsoftsTech Hi, this is a fork of ERPNext (used to contribute).
Please add the issue in the main repository https://github.com/frappe/erpnext.
