### ISSUE TITLE
Precios de los Producto Reporte

### ISSUE THREAD

**Issue by federicocalvo** [fproldan/erpnext#5]
Necesito que me asegures que funciona el reporte que te trae los últimos precios de compra.

Que está trayendo de la factura de compra, ni de orden de compra ni otra cosa. Probar con un producto con stock y sin stock. 

En realidad sospecho que no es el reporte que muestra el último precio de compra, sino la última tasa. El historial de compras reporte será el para ver el último precio sino, ordenado por fecha?

**Comment by AleGauna** [comment]
Tanto el reporte Precios de productos como el Historial de Compras esta buscando el último precio de la Orden de compra, no mira las facturas. 
A simple vista no encuentro un reporte que me muestre los precios de compra de las facturas, pero yo supongo que se debe poder configurar. Lo sigo investigando. 
Por lo pronto lo que se me ocurre para ver el ultimo precio facturado es ir al listado de compras, filtrarlo por producto, abrir el doc de la ultima fecha y ver el precio.

**Comment by fproldan** [comment]
@AleGauna Segúen el código es como decis busca en las Ordenes de Compra y Recibo de Compra. No tiene para buscar de otra forma así que hay que investigar que otros reportes hay sobre este tema (si es que existe alguno).

Si es algo que sea útil para todos se puede evaluar hacer uno nosotros.
